version: '2.3'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

